/**
 * OpenCode adapter: OpenCode has no Stop hook — the equivalent is the
 * `session.idle` event (`{ type: "session.idle", properties: { sessionID } }`
 * per @opencode-ai/sdk types), available only through its plugin system
 * (JavaScript modules in ~/.config/opencode/plugins/).
 *
 * To carry the AI's final reply (and therefore support the marker protocol),
 * the plugin also listens to `message.updated`: the last assistant message's
 * text parts are cached per session, then attached to the payload when the
 * session goes idle. The payload is piped into `donechan hook` on stdin via
 * Bun's shell `<` redirection — which only works INSIDE the template literal
 * (`$\`cmd < ${buffer}\``). A `<` placed outside the template is plain
 * JavaScript (the less-than operator) and silently delivers nothing.
 */

export function opencodePluginSource(entryPath: string, version: string): string {
  // JSON.stringify handles all path/quoting concerns for the embedded literal.
  const entryLiteral = JSON.stringify(entryPath);
  const versionLiteral = JSON.stringify(version);
  return `// DoneChan plugin — generated by \`donechan install opencode\` (v${versionLiteral})
// Pushes a ServerChan³ notification when an OpenCode session goes idle,
// carrying the assistant's final reply so the donechan marker protocol works.
// Regenerate with: donechan install opencode

const lastReply = new Map()

export const DoneChanPlugin = async ({ $, client }) => {
  return {
    event: async ({ event }) => {
      try {
        if (event.type === "message.updated") {
          const info = event.properties?.info
          if (info?.role === "assistant" && info.sessionID) {
            try {
              const msgs = await client.session.messages({ path: { id: info.sessionID } })
              const last = [...msgs.data].reverse().find((m) => m.info.role === "assistant")
              if (last) {
                lastReply.set(
                  info.sessionID,
                  (last.parts ?? [])
                    .filter((p) => p.type === "text")
                    .map((p) => p.text)
                    .join("\\n"),
                )
              }
            } catch {
              // Reply fetch is best-effort; template fallback covers it.
            }
          }
          return
        }
        if (event.type !== "session.idle") return
        const sessionID = event.properties?.sessionID ?? ""
        const payload = JSON.stringify({
          hook_event_name: "Stop",
          source_agent: "opencode",
          cwd: process.cwd(),
          session_id: sessionID,
          last_assistant_message: lastReply.get(sessionID) ?? null,
        })
        lastReply.delete(sessionID)
        await $\`node ${entryLiteral} hook < \${Buffer.from(payload)}\`.quiet()
      } catch {
        // Never break the session because a notification failed.
      }
    },
  };
};
`;
}
