/**
 * OpenCode adapter: OpenCode has no Stop hook — the equivalent is the
 * `session.idle` event (`{ type: "session.idle", properties: { sessionID } }`
 * per @opencode-ai/sdk types), available only through its plugin system
 * (JavaScript modules in ~/.config/opencode/plugins/).
 *
 * To carry the AI's final reply (and therefore support the marker protocol),
 * the plugin also listens to `message.updated`: the last assistant message's
 * text parts are cached per session, then attached to the payload when the
 * session goes idle.
 *
 * The payload is piped into `donechan hook` on stdin via node:child_process
 * spawn — NOT via Bun's `$` shell. The OpenCode desktop app runs its server
 * on Node (Electron), where plugin input `$` is explicitly `undefined`
 * (opencode guards it with `typeof Bun === "undefined" ? undefined : Bun.$`),
 * so a `$` template would throw on every event it handles and be swallowed
 * by the plugin's catch-all. node:child_process works under both runtimes.
 *
 * Note: OpenCode 1.14.x desktop builds have a separate upstream bug — the
 * plugin loads but no events are dispatched (see the README troubleshooting
 * table). Until OpenCode fixes it, no OpenCode push can fire; the spawn
 * rewrite keeps the Bun CLI path working and is what runs once events flow.
 */

export function opencodePluginSource(entryPath: string, version: string): string {
  // JSON.stringify handles all path/quoting concerns for the embedded literals.
  // nodeLiteral pins the absolute node binary captured at generation time so
  // the spawn does not depend on PATH (e.g. GUI-launched opencode processes).
  const nodeLiteral = JSON.stringify(process.execPath);
  const entryLiteral = JSON.stringify(entryPath);
  const versionLiteral = JSON.stringify(version);
  return `// DoneChan plugin — generated by \`donechan install opencode\` (v${versionLiteral})
// Pushes a ServerChan³ notification when an OpenCode session goes idle,
// carrying the assistant's final reply so the donechan marker protocol works.
// Regenerate with: donechan install opencode
//
// Spawns the donechan hook via node:child_process (works on both the Bun-based
// CLI and the Node-based desktop app, where the shell helper "$" is undefined).
// Note: OpenCode 1.14.x desktop builds don't dispatch plugin events (upstream
// bug) — until fixed, no OpenCode push can fire.

import { spawn } from "node:child_process"

const lastReply = new Map()

// Absolute node binary captured at generation time — no PATH dependence.
const nodePath = ${nodeLiteral}

export const DoneChanPlugin = async ({ client }) => {
  return {
    event: async ({ event }) => {
      try {
        if (event.type === "message.updated") {
          const info = event.properties?.info
          if (info?.role === "assistant" && info.sessionID) {
            try {
              const msgs = await client.session.messages({ path: { id: info.sessionID } })
              const last = [...msgs.data].reverse().find((m) => m.info.role === "assistant")
              if (last) {
                lastReply.set(
                  info.sessionID,
                  (last.parts ?? [])
                    .filter((p) => p.type === "text")
                    .map((p) => p.text)
                    .join("\\n"),
                )
              }
            } catch {
              // Reply fetch is best-effort; template fallback covers it.
            }
          }
          return
        }
        if (event.type !== "session.idle") return
        const sessionID = event.properties?.sessionID ?? ""
        const payload = JSON.stringify({
          hook_event_name: "Stop",
          source_agent: "opencode",
          cwd: process.cwd(),
          session_id: sessionID,
          last_assistant_message: lastReply.get(sessionID) ?? null,
        })
        lastReply.delete(sessionID)
        const child = spawn(nodePath, [${entryLiteral}, "hook"], {
          stdio: ["pipe", "ignore", "ignore"],
          windowsHide: true,
        })
        // Surface spawn failures (e.g. ENOENT) in the host log; never crash the host.
        child.on("error", (e) => console.error("donechan: spawn failed:", e))
        child.stdin?.write(payload)
        child.stdin?.end()
      } catch (e) {
        // Never break the session because a notification failed.
        console.error("donechan: plugin event failed:", e)
      }
    },
  };
};
`;
}
